//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bishojo_Game_Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bishojo_Game_Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Browse... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Composer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Composer {
            get {
                return ResourceManager.GetString("Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErogameScapeSearchModeBrand {
            get {
                return ResourceManager.GetString("ErogameScapeSearchModeBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErogameScapeSearchModeTitle {
            get {
                return ResourceManager.GetString("ErogameScapeSearchModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecutableFile {
            get {
                return ResourceManager.GetString("ExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameBrand {
            get {
                return ResourceManager.GetString("GameBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Detaile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameDetaileRegistry {
            get {
                return ResourceManager.GetString("GameDetaileRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameRegistry {
            get {
                return ResourceManager.GetString("GameRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameReleaseDate {
            get {
                return ResourceManager.GetString("GameReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Illustrator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Illustrator {
            get {
                return ResourceManager.GetString("Illustrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Data Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveDataFolder {
            get {
                return ResourceManager.GetString("SaveDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenario に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Scenario {
            get {
                return ResourceManager.GetString("Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Detaile by Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchGameDetaile {
            get {
                return ResourceManager.GetString("SearchGameDetaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Singer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Singer {
            get {
                return ResourceManager.GetString("Singer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voice Actor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VoiceActor {
            get {
                return ResourceManager.GetString("VoiceActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowCloseToolTip {
            get {
                return ResourceManager.GetString("WindowCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maxmize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowMaxmizeToolTip {
            get {
                return ResourceManager.GetString("WindowMaxmizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowMinimizeToolTip {
            get {
                return ResourceManager.GetString("WindowMinimizeToolTip", resourceCulture);
            }
        }
    }
}
