//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BishojoGameLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BishojoGameLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   BGL(仮) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BGL(仮) Version Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brand Ascending Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrandAscendingOrder {
            get {
                return ResourceManager.GetString("BrandAscendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brand Descending Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrandDescendingOrder {
            get {
                return ResourceManager.GetString("BrandDescendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeIcon {
            get {
                return ResourceManager.GetString("ChangeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Composer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Composer {
            get {
                return ResourceManager.GetString("Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnableIndex {
            get {
                return ResourceManager.GetString("EnableIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErogameScapeSearchModeBrand {
            get {
                return ResourceManager.GetString("ErogameScapeSearchModeBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErogameScapeSearchModeTitle {
            get {
                return ResourceManager.GetString("ErogameScapeSearchModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecutableFile {
            get {
                return ResourceManager.GetString("ExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameBrand {
            get {
                return ResourceManager.GetString("GameBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Detaile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameDetaileRegistry {
            get {
                return ResourceManager.GetString("GameDetaileRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameRegistry {
            get {
                return ResourceManager.GetString("GameRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameReleaseDate {
            get {
                return ResourceManager.GetString("GameReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Homepage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Illustrator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Illustrator {
            get {
                return ResourceManager.GetString("Illustrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kanji に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Kanji {
            get {
                return ResourceManager.GetString("Kanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalFile {
            get {
                return ResourceManager.GetString("LocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Game Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenGameFolder {
            get {
                return ResourceManager.GetString("OpenGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Save Data Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenSaveDataFolder {
            get {
                return ResourceManager.GetString("OpenSaveDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proxy Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release Date Ascending Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReleaseDateAscendingOrder {
            get {
                return ResourceManager.GetString("ReleaseDateAscendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release Date Descending Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReleaseDateDescendingOrder {
            get {
                return ResourceManager.GetString("ReleaseDateDescendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Data Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveDataFolder {
            get {
                return ResourceManager.GetString("SaveDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenario に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Scenario {
            get {
                return ResourceManager.GetString("Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchGame {
            get {
                return ResourceManager.GetString("SearchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Detaile by Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchGameDetaile {
            get {
                return ResourceManager.GetString("SearchGameDetaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set To Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetToDefault {
            get {
                return ResourceManager.GetString("SetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Singer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Singer {
            get {
                return ResourceManager.GetString("Singer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort By に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title Ascending Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleAscendingOrder {
            get {
                return ResourceManager.GetString("TitleAscendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title Descending Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleDescendingOrder {
            get {
                return ResourceManager.GetString("TitleDescendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateProxy {
            get {
                return ResourceManager.GetString("UpdateProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voice Actor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VoiceActor {
            get {
                return ResourceManager.GetString("VoiceActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowCloseToolTip {
            get {
                return ResourceManager.GetString("WindowCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maxmize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowMaxmizeToolTip {
            get {
                return ResourceManager.GetString("WindowMaxmizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowMinimizeToolTip {
            get {
                return ResourceManager.GetString("WindowMinimizeToolTip", resourceCulture);
            }
        }
    }
}
